# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: E2E Test

on: [push, pull_request]

jobs:
  e2e_test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: add venv
      run: |
        cd e2e_tests
    - name: install dependency
      run: |
        pip install --upgrade pip
        pip install -e .[dev]
    - name: run e2e test
      run: |
        cd e2e_tests
        nohup python3 serve.py > /dev/null 2>&1 & 
        nohup lyrebird -b > /dev/null 2>&1 & 
        is_connect=0
        for ((i=1;i<5;i++))
        do
          echo "$i"
          code=`curl -o /dev/null --retry 3 --retry-max-time 8 -s -w %{http_code} 127.0.0.1:9090/api/status`
          echo "$code"
          base=200
          if [[ $code -eq $base ]];then
            echo "is eq"
            is_connect=1
            break
          fi
          sleep 5
        done
        echo $is_connect
        if [[ $is_connect -eq 0 ]];then
          ps -ef|grep serve.py | grep -v grep|awk '{printf $2}'|xargs kill -9
          ps -ef|grep lyrebird | grep -v grep|awk '{printf $2}'|xargs kill -9
          echo "lyrebird unconneted"
          exit 8
        fi
        echo "last"
        python -m pytest .
        ps -ef|grep serve.py | grep -v grep|awk '{printf $2}'|xargs kill -9
        ps -ef|grep lyrebird | grep -v grep|awk '{printf $2}'|xargs kill -9


        
        
      